### ISSUE TITLE
Desired Amount to be Set Manually

### ISSUE THREAD

**Issue by sid9841** [santoshact360/laravel-esewa#1]
How can we set the amount manually for checkout?

**Comment by act360** [comment]
Hi Sid,

You can use the data from Request for that.

`$payment_details = [
 'tAmt' => $request->get('total_amount'),
            'amt' => $request->get('amount'),
            'pid' => $request->get('product_id'),
            'su' => "YOUR_SUCCESS_URL",
            'fu' => "YOUR_FAILURE_URL"
        ];`

Hope that helps.
Thanks

**Comment by sid9841** [comment]
Thanks! It Helped
